version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  build_and_deploy_aws:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Create CodeDeploy Deployment
          command: |
            aws deploy create-deployment \
              --application-name nginx-tutorial \
              --deployment-group-name nginx-tutorial-group \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --github-location repository=$CIRCLE_REPOSITORY_URL,commitId=$CIRCLE_SHA1
              --ignore-application-stop-failures

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy_aws:
          filters:
            branches:
              only:
                - master
